[package]
name = "phf_codegen"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.7.24"
license = "MIT"
description = "Codegen library for PHF types"
repository = "https://github.com/sfackler/rust-phf"
edition = "2018"

[dependencies]
phf_generator = { version = "0.7.24", path = "../phf_generator" }
phf_shared = { version = "0.7.24", path = "../phf_shared" }
