language: rust
sudo: false
rust:
- nightly
- beta
- stable
script:
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf_macros && cargo test))
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf_macros && cargo test --features stats))
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf_macros && cargo bench))
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf_shared && cargo build --features core))
- (test $TRAVIS_RUST_VERSION != "nightly" || (cd phf && cargo build --features core))
- (cd phf_codegen && cargo test)
- (cd phf_codegen/test && cargo test)