[package]
name = "phf"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.7.16"
license = "MIT"
description = "Runtime support for perfect hash function data structures"
repository = "https://github.com/sfackler/rust-phf"
documentation = "https://sfackler.github.io/rust-phf/doc/v0.7.16/phf"

[lib]
name = "phf"
path = "src/lib.rs"
test = false

[features]
core = ["phf_shared/core"]
unicase = ["phf_shared/unicase"]

[dependencies]
phf_shared = { version = "=0.7.16", path = "../phf_shared" }
