[package]
name = "phf"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.8.0"
license = "MIT"
description = "Runtime support for perfect hash function data structures"
repository = "https://github.com/sfackler/rust-phf"
edition = "2018"

[lib]
name = "phf"
path = "src/lib.rs"
test = false

[features]
default = ["std"]
std = ["phf_shared/std"]
uncased = ["phf_shared/uncased"]
unicase = ["phf_shared/unicase"]
macros = [
    "phf_macros",
    "proc-macro-hack",
]

[dependencies]
phf_shared = { version = "0.8.0", default-features = false }

proc-macro-hack = { version = "0.5.4", optional = true }
phf_macros = { version = "0.8.0", optional = true }

[package.metadata.docs.rs]
features = ["macros"]
