[package]
name = "phf"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.7.4"
license = "MIT"
description = "Runtime support for perfect hash function data structures"
repository = "https://github.com/sfackler/rust-phf"
documentation = "https://sfackler.github.io/rust-phf/doc/v0.7.4/phf"

[lib]
name = "phf"
path = "src/lib.rs"
test = false

[dependencies]
debug-builders = "0.1"
phf_shared = { version = "=0.7.4", path = "../phf_shared" }
