[package]
name = "unicase-example"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "^0.11.2", features = ["macros", "unicase"] }
unicase = "2"
