name: Bench
on:
  pull_request:
    types: [labeled]

jobs:
  bench_between_master_and_pr:
    if: ${{ github.event.label.name == 'run-benchmarks' }}
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - name: Setup nightly toolchain
        run: |
          rustup set profile minimal
          rustup override set nightly
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: measure benchmarks on master
        run: cargo bench
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: measure benchmarks on PR
        run: cargo bench
